[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
  "mdformat >= 1.0.0",
  "mdformat-gfm >= 1.0.0",
  "mdformat-ruff >= 0.1.0",
  "prek >= 0.4.0",
  "ruff >= 0.16.0",
  "toml-sort >= 0.24.0",
  "ty >= 0.0.70",
]
tests = [
  "pytest >= 9.1.0",
  "pytest-cov >= 7.1.0",
  "tox >= 4.59.0",
  "tox-uv >= 1.36.0",
]

[project]
authors = [
  {email = "buriedincode@duckpond.nz", name = "BuriedInCode"},
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python",
  "Topic :: Internet",
  "Typing :: Typed",
]
dependencies = [
  "numpy >= 2.5.0",
  "pillow >= 12.3.0",
  "pymupdf >= 1.28.0",
  "tessdata-eng >= 1.0.0",
]
description = "Json data of Bin rotations extracted from a Pdf."
dynamic = ["version"]
license = "MIT"
license-files = ["LICENSE"]
maintainers = [
  {email = "buriedincode@duckpond.nz", name = "BuriedInCode"},
]
name = "Bin-Lights"
readme = "README.md"
requires-python = ">= 3.14"

[project.scripts]
bin-lights = "bin_lights.main:main"

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
source = ["bin_lights"]

[tool.hatch.build.targets.sdist]
exclude = [".crow/", "output/", "sources/"]

[tool.hatch.version]
path = "bin_lights/__init__.py"

[tool.pytest.ini_options]
addopts = ["--cov"]

[tool.ruff]
fix = true
line-length = 100
output-format = "grouped"
show-fixes = true
unsafe-fixes = true

[tool.ruff.format]
docstring-code-format = true
line-ending = "native"
skip-magic-trailing-comma = true

[tool.ruff.lint]
ignore = [
  "COM812",
  "CPY001",
  "D",
  "EM101",
  "EM102",
  "FBT001",
  "FBT002",
  "PLR0913",
  "PLR2004",
  "TCH",
  "TRY003",
]
select = ["ALL"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.lint.isort]
combine-as-imports = true
split-on-trailing-comma = false

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "PLR2004", "S101"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.tomlsort]
all = true
ignore_case = true
trailing_comma_inline_array = true
overrides."tool.tox.env_list".inline_arrays = false
overrides."tool.tox.env_run_base.commands".inline_arrays = false

[tool.tox]
env_list = ["3.14"]
min_version = "4.22"

[tool.tox.env_run_base]
commands = [["pytest"]]
dependency_groups = ["tests"]
passenv = []

[tool.ty.src]
exclude = ["**/tests/"]
include = ["**/bin_lights"]
